name: Build and Push Docker image to DockerHub

on: push
jobs:
    push:
        name: Push Docker image to DockerHub repo
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Build and Push image
              uses: docker/build-push-action@v4
              with: 
                push: true
                tags:  ussnorma/multi-stage-simple-golang-webapp:latest